# **Khai báo thư viện**

In [217]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

# **Thu thập dữ liệu**

In [218]:
dataframe = pd.read_csv("mobile_prices.csv")
dataframe

battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0               842     0          2.2  ...             0     1            1
1              1021     1          0.5  ...             1     0            2
2               563     1          0.5  ...             1     0            2
3               615     1          2.5  ...             0     0            2
4              1821     1          1.2  ...             1     0            1
...             ...   ...          ...  ...           ...   ...          ...
1995            794     1          0.5  ...             1     0            0
1996           1965     1          2.6  ...             1     1            2
1997           1911     0          0.9  ...             1     0            3
1998           1512     0          0.9  ...             1     1            0
1999            510     1          2.0  ...             1     1            3

[2000 rows x 21 columns]

Đổi tên các cột

In [219]:
dataframe = dataframe.rename(index=str, columns={"battery_power": "Battery Power", "blue": "Bluetooth","clock_speed":"Clock Speed","dual_sim":"Dual Sim","fc":"Front Camera MP",
                                   "four_g":"4G","int_memory":"Internal Memory(GB)","m_dep":"Mobile Depth(CM)","mobile_wt":"Weight","n_cores":"Number of cores","pc":"Primary Camera MP"
                                   ,"px_height":"Pixel R. Height","px_width":"Pixel R. Width","ram":"RAM(MB)","sc_h":"Screen Height(cm)","sc_w":"Screen Width",
                                   "talk_time":"Longest Battery Charge","three_g":"3G","touch_screen":"Touch Screen","wifi":"WIFI","price_range":"Price Range"})

In [220]:
dataframe

Battery Power  Bluetooth  Clock Speed  ...  Touch Screen  WIFI  Price Range
0               842          0          2.2  ...             0     1            1
1              1021          1          0.5  ...             1     0            2
2               563          1          0.5  ...             1     0            2
3               615          1          2.5  ...             0     0            2
4              1821          1          1.2  ...             1     0            1
...             ...        ...          ...  ...           ...   ...          ...
1995            794          1          0.5  ...             1     0            0
1996           1965          1          2.6  ...             1     1            2
1997           1911          0          0.9  ...             1     0            3
1998           1512          0          0.9  ...             1     1            0
1999            510          1          2.0  ...             1     1            3

[2000 rows x 21 columns]

# **Chuẩn hóa dữ liệu**

Chuyển về dạng numpy

In [221]:
data = dataframe.values
print(data.shape)

(2000, 21)


Tách X, tách y

In [222]:
X = data[:,0:-1]
y = data[:,-1]
print(X[:5])
print(y[:10])

[[8.420e+02 0.000e+00 2.200e+00 0.000e+00 1.000e+00 0.000e+00 7.000e+00
  6.000e-01 1.880e+02 2.000e+00 2.000e+00 2.000e+01 7.560e+02 2.549e+03
  9.000e+00 7.000e+00 1.900e+01 0.000e+00 0.000e+00 1.000e+00]
 [1.021e+03 1.000e+00 5.000e-01 1.000e+00 0.000e+00 1.000e+00 5.300e+01
  7.000e-01 1.360e+02 3.000e+00 6.000e+00 9.050e+02 1.988e+03 2.631e+03
  1.700e+01 3.000e+00 7.000e+00 1.000e+00 1.000e+00 0.000e+00]
 [5.630e+02 1.000e+00 5.000e-01 1.000e+00 2.000e+00 1.000e+00 4.100e+01
  9.000e-01 1.450e+02 5.000e+00 6.000e+00 1.263e+03 1.716e+03 2.603e+03
  1.100e+01 2.000e+00 9.000e+00 1.000e+00 1.000e+00 0.000e+00]
 [6.150e+02 1.000e+00 2.500e+00 0.000e+00 0.000e+00 0.000e+00 1.000e+01
  8.000e-01 1.310e+02 6.000e+00 9.000e+00 1.216e+03 1.786e+03 2.769e+03
  1.600e+01 8.000e+00 1.100e+01 1.000e+00 0.000e+00 0.000e+00]
 [1.821e+03 1.000e+00 1.200e+00 0.000e+00 1.300e+01 1.000e+00 4.400e+01
  6.000e-01 1.410e+02 2.000e+00 1.400e+01 1.208e+03 1.212e+03 1.411e+03
  8.000e+00 2.000e+00 1.500e

Scale dữ liệu bằng phương pháp MinMaxScaled

In [223]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
X = minmax.fit_transform(X)
print(X[:5])

[[0.22778891 0.         0.68       0.         0.05263158 0.
  0.08064516 0.55555556 0.9        0.14285714 0.1        0.01020408
  0.17089453 0.61277392 0.28571429 0.38888889 0.94444444 0.
  0.         1.        ]
 [0.34736139 1.         0.         1.         0.         1.
  0.82258065 0.66666667 0.46666667 0.28571429 0.3        0.46173469
  0.99332443 0.63468733 0.85714286 0.16666667 0.27777778 1.
  1.         0.        ]
 [0.04141617 1.         0.         1.         0.10526316 1.
  0.62903226 0.88888889 0.54166667 0.57142857 0.3        0.64438776
  0.811749   0.6272047  0.42857143 0.11111111 0.38888889 1.
  1.         0.        ]
 [0.0761523  1.         0.8        0.         0.         0.
  0.12903226 0.77777778 0.425      0.71428571 0.45       0.62040816
  0.85847797 0.67156601 0.78571429 0.44444444 0.5        1.
  0.         0.        ]
 [0.88176353 1.         0.28       0.         0.68421053 1.
  0.67741935 0.55555556 0.50833333 0.14285714 0.7        0.61632653
  0.4753004  0.30865

Phân chia tập dữ liệu

In [224]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(\
    X, y, test_size=0.3, random_state=42)
print(X_train[:5])
print(y_train[:10])

[[0.26786907 1.         0.04       1.         0.         0.
  0.98387097 0.66666667 0.35       0.57142857 0.7        0.18571429
  0.5740988  0.90807055 0.92857143 0.44444444 0.72222222 0.
  1.         1.        ]
 [0.46492986 1.         0.         1.         0.47368421 0.
  0.29032258 0.         0.40833333 0.57142857 0.5        0.10918367
  0.80774366 0.70256547 1.         0.38888889 0.66666667 1.
  1.         1.        ]
 [0.68002672 0.         0.64       0.         0.         0.
  0.48387097 0.66666667 1.         0.         0.5        0.08571429
  0.49332443 0.70978087 0.42857143 0.55555556 0.72222222 1.
  1.         0.        ]
 [0.98196393 1.         0.         1.         0.         0.
  0.61290323 0.22222222 0.88333333 0.85714286 0.95       0.24744898
  0.28170895 0.08417958 0.21428571 0.38888889 0.83333333 1.
  1.         0.        ]
 [0.25450902 0.         0.08       1.         0.47368421 1.
  0.41935484 0.11111111 0.59166667 0.71428571 0.8        0.12653061
  0.25634179 0.13228

# **SVM**

In [225]:
from sklearn import svm

svm = svm.SVC(kernel = 'rbf', C=5)
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
accuracy_score(y_test, y_pred)

0.83

In [226]:
y_pred = svm.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.90      0.91      0.90       151
         1.0       0.76      0.79      0.77       146
         2.0       0.77      0.72      0.74       148
         3.0       0.89      0.90      0.89       155

    accuracy                           0.83       600
   macro avg       0.83      0.83      0.83       600
weighted avg       0.83      0.83      0.83       600



# **Logistic Regression**

In [227]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
accuracy_score(y_test, y_pred)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


0.9083333333333333

In [228]:
y_pred = logreg.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.95      0.97      0.96       151
         1.0       0.86      0.86      0.86       146
         2.0       0.89      0.82      0.85       148
         3.0       0.93      0.98      0.96       155

    accuracy                           0.91       600
   macro avg       0.91      0.91      0.91       600
weighted avg       0.91      0.91      0.91       600



# **Random Forest**

In [229]:
from sklearn.ensemble import RandomForestClassifier

randomf = RandomForestClassifier(n_estimators = 100)
randomf.fit(X_train, y_train)
y_pred = randomf.predict(X_test)
accuracy_score(y_test, y_pred)

0.89

In [230]:
y_pred = randomf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.95      0.96      0.95       151
         1.0       0.86      0.88      0.87       146
         2.0       0.82      0.82      0.82       148
         3.0       0.92      0.90      0.91       155

    accuracy                           0.89       600
   macro avg       0.89      0.89      0.89       600
weighted avg       0.89      0.89      0.89       600



# **Gradient Boosting Classifier**

In [231]:
from sklearn.ensemble import GradientBoostingClassifier

gbc = GradientBoostingClassifier()
gbc.fit(X_train, y_train)
y_pred = gbc.predict(X_test)
accuracy_score(y_test, y_pred)

0.8916666666666667

In [232]:
y_pred = gbc.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.96      0.93      0.95       151
         1.0       0.86      0.89      0.88       146
         2.0       0.83      0.84      0.84       148
         3.0       0.92      0.90      0.91       155

    accuracy                           0.89       600
   macro avg       0.89      0.89      0.89       600
weighted avg       0.89      0.89      0.89       600



# **Naive Bayes**

In [233]:
from sklearn.naive_bayes import GaussianNB

gaussian = GaussianNB()
gaussian.fit(X_train, y_train)
y_pred = gaussian.predict(X_test)
accuracy_score(y_test, y_pred)

0.8

In [234]:
y_pred = gaussian.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.91      0.91      0.91       151
         1.0       0.74      0.73      0.74       146
         2.0       0.67      0.72      0.70       148
         3.0       0.88      0.83      0.86       155

    accuracy                           0.80       600
   macro avg       0.80      0.80      0.80       600
weighted avg       0.80      0.80      0.80       600



# **Neural networks**

Phân bố xác suất

In [235]:
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train)
print(y_train[:2])

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]]


In [236]:
import keras
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(64, activation='relu', input_dim = 20))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(4, activation='sigmoid'))

#Compile
model.compile(loss="categorical_crossentropy", optimizer = "adam", metrics=['accuracy'])

#Fit
model.fit(X_train, y_train, epochs= 100, batch_size= 10, verbose =0)

y_pred = model.predict(X_test)
y_pred = y_pred.argmax(axis=1)
accuracy_score(y_test, y_pred)

0.9233333333333333

# **Thay vào input mới**

Tự chọn các input mới bằng thủ công và cho vào list

In [245]:
input_new = [[0.76486306, 0, 0.8, 0, 0.15789474, 1,0.37096774,0.55555556, 1, 0.14285714, 0.25, 0.10765306, 0.73965287, 0.11491181, 0.21428571, 0.33333333, 0.5, 1, 1, 0],
     [0.68002672, 0, 0.64, 0, 0, 0, 0.48387097, 0.66666667, 1, 0, 0.5, 0.08571429, 0.49332443, 0.70978087, 0.42857143, 0.55555556, 0.72222222, 1, 1, 0],
     [0.46492986, 1, 0.04, 1, 0.47368421, 1, 0.41935484, 0.22222222, 0.59166667, 0.57142857, 0.7, 0.10918367, 0.80774366 , 0.1322822, 0.21428571, 0.38888889, 0.66666667, 1, 1, 1],
     [0.0741483, 1, 0.56, 1, 0.31578947, 0, 0.22580645, 0.22222222, 0.18333333, 0.85714286, 0.35, 0.69387755, 0.92857143, 0.77632282, 0.21428571, 0.22222222, 0.05555556, 0, 0, 0],
     [0.98263193, 0, 0.96, 0, 0.47368421, 0, 0.19354839, 0.33333333, 0.96666667, 0.85714286, 0.9, 0.1494898, 0.30173565, 0.28327098, 0.21428571, 0.05555556, 0.33333333, 1, 1, 0],
     [0.6746827, 0, 0.8, 1, 0.15789474, 0, 0.30645161, 0.11111111, 0.28333333, 0.28571429, 0.9, 0.74234694, 0.98931909, 0.93265633, 0.35714286, 0, 0.16666667, 1, 0, 0],
     [0.93587174, 0, 0.92, 1, 0.31578947, 0, 0.77419355, 0.77777778, 0.36666667, 1, 0.45, 0.58265306, 0.59612817, 0.0232496, 0.42857143, 0.44444444, 0.88888889, 0, 1, 0],
     [0.10888444, 1, 0.24, 1, 0.05263158, 1, 0.79032258, 0, 0.25, 0.85714286, 0.2, 0.35765306, 0.65287049, 0.90138963, 1, 0.83333333, 0.22222222, 1, 1, 1],
     [0.51235805,1, 0.96, 0, 0.47368421, 1, 0.64516129, 0.88888889, 0.85, 0.71428571, 0.85, 0.18367347, 0.27503338, 0.18038482, 0.42857143, 0.27777778, 1, 1, 1,0],
     [0.83299933, 0, 0.48, 1, 0.31578947, 1, 0.19354839, 0.44444444, 0.55, 0.28571429, 0.35, 0.43826531, 0.48998665, 0.9919829, 0.78571429, 0.66666667, 0.05555556, 1, 0,1]]



Chuyển về dạng numpy array

In [246]:
input_new = np.array(input_new)

Đưa input vào phương pháp có độ chính xác cao nhất

In [247]:
y_pred_new = model.predict(input_new)
y_pred_new = y_pred_new.argmax(axis=1)
print(y_pred_new)

[0 2 0 3 1 3 0 3 0 3]


In [248]:
y_pred_new = y_pred_new.tolist()
for i in range(len(y_pred_new)):
  if(y_pred_new[i] == 0):
    y_pred_new[i] = 'low cost'
  elif(y_pred_new[i] == 1):
    y_pred_new[i] = 'medium cost'
  elif(y_pred_new[i] == 2):
    y_pred_new[i] = 'high cost'
  else:
    y_pred_new[i] = 'very high cost'
print(y_pred_new)

['low cost', 'high cost', 'low cost', 'very high cost', 'medium cost', 'very high cost', 'low cost', 'very high cost', 'low cost', 'very high cost']
